dalero/urls.py
from django.conf.urls import patterns, include, url
from dalero import settings

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin

#admin.autodiscover()
from dalero.settings import STATIC_ROOT

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'website.views.home', name='home'),
    url(r'^users/', include('usuarios.urls')),
    url(r'^app/', include('website.app_urls')),
    url(r'^geo/', include('geo.urls')),
    url(r'^comentarios/', include('comentarios.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT,
                                                                   'show_indexes': True}),
    )

geo/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^buscar_estacionmientos/$','geo.views.buscar_estacionmientos'),
)

parkero/parkero/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'website.views.inicio'),
    url(r'^ahora$', 'website.views.ahora'),
    # url(r'^parkero/', include('parkero.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

usuarios/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('',

    url(r'^login/$','usuarios.views.login'),
    url(r'^logout/$','usuarios.views.logout'),

    url(r'^twitter_connect/$','usuarios.views.twitter_connect'),
    url(r'^twitter_callback/$','usuarios.views.twitter_callback'),
    url(r'^facebook_connect/$','usuarios.views.facebook_connect'),
    url(r'^facebook_callback/$','usuarios.views.facebook_callback'),

    url(r'^admin/crear_estacionamiento/$','usuarios.views.crear_estacionamiento'),
    url(r'^admin/listar_estacionamientos/(?P<page>\d+)?','usuarios.views.listar_estacionamientos'),
    url(r'^admin/editar_estacionamiento/(?P<id>\d+)/$','usuarios.views.editar_estacionamiento'),
    url(r'^admin/eliminar_estacionamiento/(?P<id>\d+)/$','usuarios.views.eliminar_estacionamiento'),

    url(r'^admin/listar_comentarios/(?P<park>\d+)/(?P<page>\d+)?','usuarios.views.listar_comentarios'),
    url(r'^admin/eliminar_comentario/(?P<id>\d+)/(?P<id_comentario>\d+)/$','usuarios.views.eliminar_comentario'),

    url(r'^admin/listar_usuarios/(?P<page>\d+)?','usuarios.views.listar_usuarios'),
    url(r'^admin/eliminar_usuario/(?P<id>\d+)/$','usuarios.views.eliminar_usuario'),

    url(r'^admin/editar_estacionamiento/(?P<id>\d+)/$','usuarios.views.editar_estacionamiento'),

    url(r'^park/editar_estacionamiento/$','usuarios.views.editar_estacionamiento'),
    url(r'^park/listar_comentarios/(?P<park>\d+)/(?P<page>\d+)?','usuarios.views.listar_comentarios'),
    url(r'^park/denunciar_comentario/(?P<id>\d+)/$','usuarios.views.denunciar_comentario'),
)

usuarios/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.
from django.db.models import Avg

class UsuarioBase(models.Model):
    nombre_usuario = models.CharField(max_length=100)
    password = models.CharField(max_length=128, null=True, blank=True)
    creacion = models.DateTimeField(auto_now=False, auto_now_add=True)
    ultimo_acceso = models.DateTimeField(auto_now=True, auto_now_add=True)
    administrador = models.BooleanField(default=False)
    activo = models.BooleanField(default=True)
    correo = models.EmailField(null=True, blank=True)

    def login(self, request):
        request.session['SESSION_KEY'] = self.id
        self.save()
        return True

class IntentosIngreso(models.Model):
    ip = models.IPAddressField(blank=False, null=False, db_index=True)
    fecha = models.DateTimeField(auto_created=True)

class Cliente(UsuarioBase):
    facebook_id = models.CharField(max_length=100, blank=True, null=True)
    facebook_accesstoken = models.CharField(max_length=200, blank=True, null=True)
    facebook_code = models.CharField(max_length=400, blank=True, null=True)
    twitter_id = models.CharField(max_length=100, blank=True, null=True)
    twitter_accesstoken = models.CharField(max_length=200, blank=True, null=True)
    twitter_secrettoken = models.CharField(max_length=200, blank=True, null=True)

    def to_dict(self):
        data = {'nombre_usuario' : self.nombre_usuario,
                'facebook' : self.facebook_id is not None,
                'id' : self.id,
                'activo' : self.activo,
                'twitter' : self.twitter_id is not None}
        return data

class Estacionamiento(UsuarioBase):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField(max_length=200)
    latitud = models.FloatField(db_index=True, max_length=25)
    longitud = models.FloatField(db_index=True, max_length=25)
    motos = models.BooleanField(default=False)
    camiones = models.BooleanField(default=False)
    sin_techo = models.BooleanField(default=False)

    def to_dict(self, admin=False):
        puntos = self.puntos_set.all().aggregate(Avg('puntos'))['puntos__avg']
        data = {
            'nombre' : self.nombre,
            'descripcion' : self.descripcion,
            'latitud' : str(self.latitud),
            'longitud' : str(self.longitud),
            'puntos' : int(round(puntos, 2)) if puntos is not None else 0,
            'motos' : self.motos,
            'camiones' : self.camiones,
            'sin_techo' : self.sin_techo,
            'id' : self.id,
            'comentarios' : self.comentarios_set.all().count()
        }
        if admin:
            data.update({'correo' : self.correo,
                         'nombre_usuario' : self.nombre_usuario,
                         'activo' : self.activo})

        return data

usuarios/views.py
# -*- coding: utf-8 -*-
import hashlib
import json
import urllib
import urlparse
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render_to_response
from django.template import RequestContext
import tweepy
from comentarios.models import Comentarios
from dalero.settings import TWITTER, FACEBOOK
from usuarios.forms import FormEstacionamiento
from usuarios.models import Estacionamiento, UsuarioBase, Cliente
from usuarios.permisos import *


def twitter_connect(request):
    """
    Inicio del proceso oauth de Twitter
    Se obtiene el request_token para luego redireccionar al usuario a la página para solicitar permiso de acceso
    Libreria tweepy
    """

    try:
        auth = tweepy.OAuthHandler(TWITTER['KEY'], TWITTER['SECRET'], TWITTER["CALLBACK"])
        redirect_url = auth.get_authorization_url()
        rkey = auth.request_token.key
        rsecret = auth.request_token.secret
        request.session['tw_rt'] = "%s::%s"%(rkey, rsecret)
        return HttpResponseRedirect(redirect_url)
    except:
        return HttpResponseRedirect('/?error_twitter')

def twitter_callback(request):
    """
    Una vez el usuario permise o no el acceso a su cuenta de Twitter esta vista revisa si concedio permisos o no
    En caso afirmativo busca a un usuario con ese id de Twitter para crear la sesion, de no existir crea al usuario
    """
    retorno = HttpResponseRedirect('/')
    try:
        s = request.session['tw_rt']
        tokens = s.split('::')
        request_token = tokens[0]
        request_secret = tokens[1]

        if 'oauth_token' in request.GET and 'oauth_verifier' in request.GET:
            oauth_verifier = request.GET['oauth_verifier']
            oauth = tweepy.OAuthHandler(TWITTER['KEY'], TWITTER['SECRET'])
            oauth.set_request_token(request_token, request_secret)
            oauth.get_access_token(oauth_verifier)
            api = tweepy.API(oauth)
            tw_user = api.verify_credentials()
            try:
                cliente = Cliente.objects.get(twitter_id=tw_user.id)
                cliente.login(request)
            except Cliente.DoesNotExist:
                accesstoken = oauth.access_token.key
                secret = oauth.access_token.secret
                cliente = Cliente(nombre_usuario="%s_tc"%tw_user.screen_name,
                    twitter_id=tw_user.id,
                    twitter_accesstoken=accesstoken,
                    twitter_secrettoken=secret)
                cliente.save()
                cliente.login(request)
            retorno = HttpResponseRedirect('/app/')
    except:
        retorno = HttpResponseRedirect('/?error_twitter')
    del request.session['tw_rt']
    return retorno

def facebook_connect(request):
    """
    Inicio del proceso oauth de Facebook
    Se obtiene el request_token para luego redireccionar al usuario a la página para solicitar permiso de acceso
    """
    facebook_oauth = "https://www.facebook.com/dialog/oauth?client_id=%s&redirect_uri=%s&scope=email,publish_stream,offline_access"\
                     %(FACEBOOK["KEY"],
                       FACEBOOK["CALLBACK"])
    return HttpResponseRedirect(facebook_oauth)

def facebook_callback(request):
    """
    Una vez el usuario permise o no el acceso a su cuenta de Facebook esta vista revisa si concedio permisos o no
    En caso afirmativo busca a un usuario con ese id de Facebook para crear la sesion, de no existir crea al usuario
    """
    code = None if 'code' not in request.GET else request.GET['code']
    retorno = HttpResponseRedirect('/?error_facebook')
    try:
        if code is not None:
            args = dict(client_id=FACEBOOK["KEY"],
                        redirect_uri=FACEBOOK["CALLBACK"],
                        client_secret=FACEBOOK["SECRET"],
                        code=code)
            response = urlparse.parse_qs(urllib.urlopen("https://graph.facebook.com/oauth/access_token?%s"%urllib.urlencode(args)).read())

            access_token = response["access_token"][-1]

            if access_token is not None:
                fb_user = json.load(urllib.urlopen("https://graph.facebook.com/me?%s"%urllib.urlencode(dict(access_token=access_token))))
                if 'id' in fb_user:
                    try:
                        cliente = Cliente.objects.get(facebook_id=fb_user['id'])
                        cliente.login(request)
                    except Cliente.DoesNotExist:
                        cliente = Cliente(nombre_usuario="%s_fb"%(fb_user['username'] if 'username' in fb_user else fb_user['id']),
                            facebook_id=fb_user['id'],
                            facebook_accesstoken=access_token,
                            facebook_code=code)
                        cliente.save()
                        cliente.login(request)
                        request.session['tipo'] = 'cliente'
                    retorno = HttpResponseRedirect('/app/')
    except:
        pass
    return retorno

@user_passes_test(es_administrador, login_url='/users/login/')
def crear_estacionamiento(request):
    """
    Vista para crear estacionamiento
    Se valida si existe un UsuarioBase con el email y nombre_usuario pasado (deben ser unicos)
    Se crea el password tipo nombre_usuario12345
    """
    errors = {}
    if request.method != 'POST':
        form = FormEstacionamiento()
    else:
        form = FormEstacionamiento(data=request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data

            if UsuarioBase.objects.all().filter(nombre_usuario=clean_data['nombre_usuario']).exists():
                errors = {'nombre_usuario' : {'as_text':'* Nombre de usuario usado'}}
            elif UsuarioBase.objects.all().filter(correo=clean_data['correo']).exists():
                errors = {'correo' : {'as_text':'* Correo electrónico usado'}}
            else:
                password = __new_password(user=clean_data['nombre_usuario'])
                estacionamiento = Estacionamiento(
                    nombre_usuario=clean_data['nombre_usuario'],
                    password=password,
                    correo=clean_data['correo'],
                    descripcion=clean_data['descripcion'],
                    nombre=clean_data['nombre'],
                    latitud=clean_data['latitud'],
                    longitud=clean_data['longitud'],
                    motos=clean_data['motos'],
                    camiones=clean_data['camiones'],
                    sin_techo=clean_data['sin_techo'])
                estacionamiento.save()

                return HttpResponseRedirect('/users/admin/listar_estacionamientos/')
        else:
            errors = form.errors
    return render_to_response('usuarios/crear_editar_estacionamiento.html', {'form' : form, 'errors' : errors, 'crear' : True}, context_instance=RequestContext(request))

@user_passes_test(es_administrador, login_url='/users/login/')
def listar_estacionamientos(request, page=1):
    """
    Vista para mostrar los estacionamientos registrados con paginacion
    """
    estacionamientos = Estacionamiento.objects.all()

    paginator = Paginator(estacionamientos, 20)
    
    try:
        page = int(page)
    except:
        page = 1

    try:
        pagina = paginator.page(page)
    except (EmptyPage, InvalidPage):
        pagina = paginator.page(paginator.num_pages)

    pagination = {'object_list': [x.to_dict(admin=True) for x in pagina.object_list],
                          'has_prev': pagina.has_previous(),
                          'has_next': pagina.has_next(),
                          'prev_page': pagina.previous_page_number() if pagina.has_previous() else None,
                          'next_page': pagina.next_page_number() if pagina.has_next() else None,
                          'page': pagina.number,
                          'num_pages': pagina.paginator.num_pages,
    }
    return render_to_response('usuarios/listar_estacionamientos.html', {'pagination' : pagination,}, context_instance=RequestContext(request))

@user_passes_test(es_estacionamiento, login_url='/users/login/')
def editar_estacionamiento(request, id=None):
    """
    Vista para editar estacionamiento
    Podran usar esta vista tanto estacionamientos como administrador
    """
    errors = {}
    es_estac = Estacionamiento.objects.all().filter(usuariobase_ptr_id=request.user.id).exists()
    try:
        if es_estac:
            estacionamiento = request.user.estacionamiento
        else:
            estacionamiento = Estacionamiento.objects.get(pk=id)
        if request.method != 'POST':
            initial = {'nombre' : estacionamiento.nombre,
                       'nombre_usuario' : estacionamiento.nombre_usuario,
                       'correo' : estacionamiento.correo,
                       'descripcion' : estacionamiento.descripcion,
                       'motos' : estacionamiento.motos,
                       'camiones' : estacionamiento.camiones,
                       'sin_techo' : estacionamiento.sin_techo,
                       'id' : estacionamiento.id}
            if not es_estac:
                initial.update({'latitud' : estacionamiento.latitud,
                                'longitud' : estacionamiento.longitud,})
            form = FormEstacionamiento(initial=initial,
                                        edit=True,
                                        parking=es_estac)
        else:
            form = FormEstacionamiento(data=request.POST, edit=True, parking=es_estac)
            if form.is_valid():
                clean_data = form.cleaned_data
                if Estacionamiento.objects.all().exclude(pk=estacionamiento.id).filter(correo=clean_data['correo']).exists():
                    errors = {'correo' : {'as_text':'* Correo electrónico usado'}}
                else:
                    estacionamiento.descripcion = clean_data['descripcion']

templates/usuarios/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Sistema De Identificación De Puntos De Estacionamientos Mediante El Uso De Geo-Localización En La Parroquia La Candelaria Del Distrito Capital | Admin</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

    <style>body {padding-top: 60px;padding-bottom: 40px;}</style>
    <link rel="stylesheet" href="/static/css/bootstrap-responsive.min.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <script src="/static/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>
</head>
<body>
<!--[if lt IE 7]>
    <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
<![endif]-->

<!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="#">Administrador Estacionamientos</a>
            <ul class="nav">
                {% if not es_estacionamiento %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Estacionamientos
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <a href="/users/admin/crear_estacionamiento/">Crear</a>
                        <a href="/users/admin/listar_estacionamientos/">Lista</a>
                    </ul>
                </li>
                <li><a href="/users/admin/listar_usuarios/">Usuarios</a></li>
                {% else %}
                <li><a href="/users/park/listar_comentarios/{{ estacionamiento.id }}/">Listar Comentarios</a></li>
                {% endif %}
                <li><a href="/">Inicio</a></li>
                <li><a href="/users/logout/">Salir</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="container">
    {% block content %}{% endblock %}
    <footer>
        <p></p>
    </footer>

</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/static/js/vendor/jquery-1.8.2.min.js"><\/script>')</script>
<script src="/static/js/vendor/bootstrap.min.js"></script>
{% block js %}{% endblock %}
</body>
</html>

templates/usuarios/crear_editar_estacionamiento.html
{% extends 'usuarios/base.html' %}

{% block content %}

<form action="{{ action }}" method="post">
    <fieldset>
        <legend>{% if crear %}Crear {% else %}Editar {% endif %}Estacionamiento</legend>
        {% csrf_token %}
        <div class="control-group{% if errors.nombre_usuario %} error{% endif %}" id="control_{{ form.nombre_usuario.name }}">
            <label class="control-label" for="{{ form.nombre_usuario.name }}">{{ form.nombre_usuario.label }}</label>
            <div class="controls">
                {{ form.nombre_usuario }}
                {% if errors.nombre_usuario %}<span class="help-inline">{{ errors.nombre_usuario.as_text }}</span>{% endif %}
            </div>
        </div>
        <div class="control-group{% if errors.correo %} error{% endif %}" id="control_{{ form.correo.name }}">
            <label class="control-label" for="{{ form.correo.name }}">{{ form.correo.label }}</label>
            <div class="controls">
                {{ form.correo }}
                {% if errors.correo %}<span class="help-inline">{{ errors.correo.as_text }}</span>{% endif %}
            </div>
        </div>
        <div class="control-group{% if errors.nombre %} error{% endif %}" id="control_{{ form.nombre.name }}">
            <label class="control-label" for="{{ form.nombre.name }}">{{ form.nombre.label }}</label>
            <div class="controls">
                {{ form.nombre }}
                {% if errors.nombre %}<span class="help-inline">{{ errors.nombre.as_text }}</span>{% endif %}
            </div>
        </div>
        <div class="control-group{% if errors.descripcion %} error{% endif %}" id="control_{{ form.descripcion.name }}">
            <label class="control-label" for="{{ form.descripcion.name }}">{{ form.descripcion.label }}</label>
            <div class="controls">
                {{ form.descripcion }}
                {% if errors.descripcion %}<span class="help-inline">{{ errors.descripcion.as_text }}</span>{% endif %}
            </div>
        </div>
        {% if crear %}
        <div class="control-group{% if errors.latitud %} error{% endif %}" id="control_{{ form.latitud.name }}">
            <label class="control-label" for="{{ form.latitud.name }}">{{ form.latitud.label }}</label>
            <div class="controls">
                {{ form.latitud }}
                {% if errors.latitud %}<span class="help-inline">{{ errors.latitud.as_text }}</span>{% endif %}
            </div>
        </div>
        <div class="control-group{% if errors.longitud %} error{% endif %}" id="control_{{ form.longitud.name }}">
            <label class="control-label" for="{{ form.longitud.name }}">{{ form.longitud.label }}</label>
            <div class="controls">
                {{ form.longitud }}
                {% if errors.longitud %}<span class="help-inline">{{ errors.longitud.as_text }}</span>{% endif %}
            </div>
        </div>
        {% endif %}
        <div class="control-group{% if errors.motos %} error{% endif %}" id="control_{{ form.motos.name }}">
            <label class="control-label" for="{{ form.motos.name }}">{{ form.motos.label }}</label>
            <div class="controls">
                {{ form.motos }}
                {% if errors.motos %}<span class="help-inline">{{ errors.motos.as_text }}</span>{% endif %}
            </div>
        </div>
        <div class="control-group{% if errors.camiones %} error{% endif %}" id="control_{{ form.camiones.name }}">
            <label class="control-label" for="{{ form.camiones.name }}">{{ form.camiones.label }}</label>
            <div class="controls">
                {{ form.camiones }}
                {% if errors.camiones %}<span class="help-inline">{{ errors.camiones.as_text }}</span>{% endif %}
            </div>
        </div>
        <div class="control-group{% if errors.sin_techo %} error{% endif %}" id="control_{{ form.sin_techo.name }}">
            <label class="control-label" for="{{ form.sin_techo.name }}">{{ form.sin_techo.label }}</label>
            <div class="controls">
                {{ form.sin_techo }}
                {% if errors.sin_techo %}<span class="help-inline">{{ errors.sin_techo.as_text }}</span>{% endif %}
            </div>
        </div>
        {{ form.id }}
        <button type="submit" class="btn">Enviar</button>
    </fieldset>
</form>
{% endblock %}
{% block js %}
    {% if crear %}
    <script>
        $(document).ready(function(){
            navigator.geolocation.getCurrentPosition(function (position) {
                var $lat = position.coords.latitude;
                var $long = position.coords.longitude;
                $('#id_latitud').val($lat).toFixed(5);
                $('#id_longitud').val($long).toFixed(5);
                alert('sadf')
            },
            function(){alert('Error al obtener posición');},
            { enableHighAccuracy:true }
            );
        });
    </script>
    {% endif %}
{% endblock %}

templates/usuarios/listar_comentarios.html
{% extends 'usuarios/base.html' %}

{% block content %}

    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                {% if not es_estacionamiento %}<th>Estacionamiento</th>{% endif %}
                <th>Usuario</th>
                <th>Fecha</th>
                <th>Comentario</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for comm in pagination.object_list %}
            <tr>
            {% if not es_estacionamiento %}
                <td><a href="/users/admin/editar_estacionamiento/{{ estacionamiento.id }}">{{ comm.estacionamiento.nombre }}</a></td>
            {% endif %}
                <td>{{ comm.cliente.nombre_usuario }}</td>
                <td>{{ comm.fecha }}</td>
                <td>{{ comm.contenido }}</td>
                <td>
                    {% if not es_estacionamiento %}
                    <a href="/users/admin/eliminar_comentario/{{ estacionamiento.id }}/{{ comm.id }}/">borrar</a>
                    {% else %}
                    <a href="/users/park/denunciar_comentario/{{ comm.id }}/">{% if comm.spam %}no es spam{% else %}spam{% endif %}</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <ul class="pager">
        {% if pagination.has_prev %}<li><a href="/users/admin/listar_comentarios/{{ estacionamiento.id }}/{{ pagination.prev_page }}/">Anterior</a></li>{% endif %}
        {% if pagintion.has_next %}<li><a href="/users/admin/listar_comentarios/{{ estacionamiento.id }}/{{ pagination.next_page }}/">Próxima</a></li>{% endif %}
    </ul>
{% endblock %}

templates/usuarios/listar_estacionamientos.html
{% extends 'usuarios/base.html' %}

{% block content %}

    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Nombre Usuario</th>
                <th>Correo</th>
                <th>Descripción</th>
                <th>Latitud</th>
                <th>Longitud</th>
                <th>Motos</th>
                <th>Camiones</th>
                <th>Sin techo</th>
                <th>Comentarios</th>
                <th>Puntos</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for est in pagination.object_list %}
            <tr>
                <td>{{ est.nombre }}</td>
                <td>{{ est.nombre_usuario }}</td>
                <td>{{ est.correo }}</td>
                <td>{{ est.descripcion }}</td>
                <td>{{ est.latitud }}</td>
                <td>{{ est.longitud }}</td>
                <td>{% if est.motos %}X{% endif %}</td>
                <td>{% if est.camiones %}X{% endif %}</td>
                <td>{% if est.sin_techo %}X{% endif %}</td>
                <td><a href="/users/admin/listar_comentarios/{{ est.id }}/">{{ est.comentarios }}</a></td>
                <td>{{ est.puntos }}</td>
                <td>
                    <a href="/users/admin/editar_estacionamiento/{{ est.id }}/">editar</a>
                    <a href="/users/admin/eliminar_estacionamiento/{{ est.id }}/">{% if est.activo %}desactivar{% else %}activar{% endif %}</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <ul class="pager">
        {% if pagination.has_prev %}<li><a href="/users/admin/listar_estacionamientos/{{ pagination.prev_page }}/">Anterior</a></li>{% endif %}
        {% if pagintion.has_next %}<li><a href="/users/admin/listar_estacionamientos/{{ pagination.next_page }}/">Próxima</a></li>{% endif %}
    </ul>
{% endblock %}

templates/usuarios/listar_usuarios.html
{% extends 'usuarios/base.html' %}

{% block content %}

    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Nombre de Usuario</th>
                <th>Facebook</th>
                <th>Twitter</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for user in pagination.object_list %}
            <tr>
                <td>{{ user.nombre_usuario }}</td>
                <td>{% if user.facebook %}X{% endif %}</td>
                <td>{% if user.twitter %}X{% endif %}</td>
                <td>
                    <a href="/users/admin/eliminar_usuario/{{ user.id }}/">{% if user.activo %}desactivar{% else %}activar{% endif %}</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <ul class="pager">
        {% if pagination.has_prev %}<li><a href="/users/admin/listar_estacionamientos/{{ pagination.prev_page }}/">Anterior</a></li>{% endif %}
        {% if pagintion.has_next %}<li><a href="/users/admin/listar_estacionamientos/{{ pagination.next_page }}/">Próxima</a></li>{% endif %}
    </ul>
{% endblock %}